spring:
  thymeleaf:
    prefix: classpath:/WEB-INF/views/
    suffix:
    view-names: '*.html'
    mode: LEGACYHTML5
    cache: false
    http:
      multipart:
        maxFileSize: 500Mb
        maxRequestSize: 500Mb